language: cpp
sudo: required
dist: trusty
compiler:
- g++
- clang++
os:
- linux
addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies_linux.sh; fi;
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/dependencies_osx.sh; fi;
script:
- ./scripts/build.sh
